### ISSUE TITLE
Question: Can I use this with Emotion?

### ISSUE THREAD

**Issue by lifeiscontent** [braposo/graphql-css#7]
Hi, kentcdodds recently stopped maintaining glamorous so I was wondering if its possible to use this with emotion?

or better yet, maybe there's a way where this library generates the CSS and the returned data from the GQL query is the actual CSS class which gets rendered into the react element.

that way there's no need for emotion/glamorous elements. and you can use things like `ref` without issues (currently you have to use innerRef for emotion) which is a pain because if you're using elements that aren't emotion elements you have to check if its a emotion element or not and these kinds of things should be unobservable to the developer.

**Comment by lifeiscontent** [comment]
ping @braposo

**Comment by braposo** [comment]
Hey @lifeiscontent, thanks for your question! That's something I've been considering since the deprecation of glamorous so it's probably happening soon.

In the meantime you could always wrap the generated component with emotion, which I know isn't ideal but works.

```jsx
import styled from "react-emotion";

const Text = gqlCSS(styles)(textStyles);

const StyledText = styled(Text)({
	...yourStyles
});
```

**Comment by lifeiscontent** [comment]
@braposo I'd love to talk to you more about this concept you've put together.

One of the things I think would be really powerful here is to create an adapter for the initializer. e.g.

``` js
import GraphQLCSS from 'graphql-css';
import { css } from 'emotion';

const CSSQuery = new GraphQLCSS({css: css});

const MyComp = (props) => (
  <CSSQuery query={...} variables={...}>
    {className => <div className={className} {...props} />}
  </CSSQuery>
);
```

I think something like this would be super powerful. Because of a few things.

1. It removes the need for an extra adapter into the react eco system (emotion, styled-components, etc).
2. the query generates the class.
3. you can use pure react components and the API stays the same for other Query components.

what do you think about something like this?

**Comment by braposo** [comment]
@lifeiscontent with the new v2 API you can now use `getStyles` to make it work with `emotion`.

```jsx
import useGqlCSS, { gql } from "graphql-css";
import styled from "@emotion/styled";
...
const query = gql`
    {
        color: colors {
            green
        }
    }
`;
const { getStyles } = useGqlCSS(styles);
const StyledComponent = styled.div(getStyles(query));
```
